---
- name: Configure Infra Box.
  hosts: infrabox
  become: true

  pre_tasks:
    - name: Load configuration from config.yaml.
      ansible.builtin.include_vars: "{{ item }}"
      loop:
        - config.yaml

    - name: Ensure apt cache is up to date.
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

  tasks:
    - name: Setup issue file
      ansible.builtin.import_tasks: tasks/issue.yaml
    
    - name: Setup Docker
      ansible.builtin.import_tasks: tasks/docker.yaml

    - name: Setup Traefik
      ansible.builtin.import_tasks: tasks/traefik.yaml

    - name: Setup Dockge
      ansible.builtin.import_tasks: tasks/dockge.yaml

    - name: Setup Pihole
      ansible.builtin.import_tasks: tasks/pihole.yaml
    
    - name: Setup PhpIpam
      ansible.builtin.import_tasks: tasks/phpipam.yaml

    - name: Setup Tftp
      ansible.builtin.import_tasks: tasks/tftp.yaml

    - name: Setup Directory Browser
      ansible.builtin.import_tasks: tasks/directorybrowser.yaml

    - name: Setup Librenms
      ansible.builtin.import_tasks: tasks/librenms.yaml
    
    - name: "Create {{ infrabox_user_name }} user"
      ansible.builtin.import_tasks: tasks/infraboxuser.yaml
      when: infrabox_user_enable