[project]
name = "infra-box"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ansible>=11.2.0",
    "ansible-pylibssh>=1.2.2",
    "passlib>=1.7.4",
]
